title = "RHYTHMHEAVEN"
code = "YLZE"
maker = "01"
unit_code = 0
device_type = 0
capacity = "256M"
revision = 0
arm9_unkfunc = "func_02000aac"
arm9_moduleparams = "ModuleParams"
arm9_footer = true

[banner]
version = 1
title = "Rhythm Heaven\nNintendo"
icon = "rhds.png"